version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  dashboard:
    build: .
    ports:
      - "8502:8501"
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]